### ISSUE TITLE
Module Error on Instalacion

### ISSUE THREAD

**Issue by s4msagaz** [tryton-ar/bank_ar#1]
19664 139989088093952 [2016-10-07 21:46:44,631] ERROR trytond.protocols.dispatcher <class 'trytond.ir.module.ir.module.install_upgrade'>.execute(_(22, {u'start': {u'module_info': u'bank_ar: to install', u'id': -15}}, u'upgrade', {u'date_format': u'%d/%m/%Y', u'language': u'es_AR', u'locale': {u'date': u'%d/%m/%Y', u'thousands_sep': u'.', u'decimal_point': u',', u'grouping': [3, 3, 0]}, u'language_direction': u'ltr', u'company.rec_name': u'Jose Luis Zanotti', u'active_model': u'ir.module', u'groups': [1, 6, 4, 3, 2, 5], u'action_id': 42, u'employee': None, u'active_ids': [15], u'company': 1, u'active_id': 15}), *_{}) from admin@192.168.0.202//tryton40/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/trytond/protocols/dispatcher.py", line 201, in _dispatch
    result = rpc.result(meth(_c_args, *_c_kwargs))
  File "/usr/local/lib/python2.7/dist-packages/trytond/wizard/wizard.py", line 275, in execute
    return wizard._execute(state_name)
  File "/usr/local/lib/python2.7/dist-packages/trytond/wizard/wizard.py", line 306, in _execute
    result = self._execute(transition())
  File "/usr/local/lib/python2.7/dist-packages/trytond/ir/module.py", line 570, in transition_upgrade
    pool.init(update=update, lang=lang)
  File "/usr/local/lib/python2.7/dist-packages/trytond/pool.py", line 155, in init
    lang=lang)
  File "/usr/local/lib/python2.7/dist-packages/trytond/modules/__init__.py", line 434, in load_modules
    _load_modules()
  File "/usr/local/lib/python2.7/dist-packages/trytond/modules/__init__.py", line 398, in _load_modules
    load_module_graph(graph, pool, update, lang)
  File "/usr/local/lib/python2.7/dist-packages/trytond/modules/__init__.py", line 251, in load_module_graph
    tryton_parser.parse_xmlstream(fp)
  File "/usr/local/lib/python2.7/dist-packages/trytond/convert.py", line 447, in parse_xmlstream
    self.sax_parser.parse(source)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 320, in end_element
    self._cont_handler.endElement(name)
  File "/usr/local/lib/python2.7/dist-packages/trytond/convert.py", line 507, in endElement
    self.taghandler = self.taghandler.endElement(name)
  File "/usr/local/lib/python2.7/dist-packages/trytond/convert.py", line 289, in endElement
    self.model.__name__, self.values, self.xml_id)
  File "/usr/local/lib/python2.7/dist-packages/trytond/convert.py", line 693, in import_record
    self.create_records(model, [values], [fs_id])
  File "/usr/local/lib/python2.7/dist-packages/trytond/convert.py", line 699, in create_records
    records = Model.create(vlist)
  File "/usr/local/lib/python2.7/dist-packages/trytond_party-4.0.2-py2.7.egg/trytond/modules/party/party.py", line 164, in create
    return super(Party, cls).create(vlist)
  File "/usr/local/lib/python2.7/dist-packages/trytond/model/modelsql.py", line 522, in create
    field = cls._fields[fname]
KeyError: u'iva_condition'

**Comment by lukio** [comment]
Lo más probable es que estuviera faltando instalar previamente el módulo party_ar.
Cierro el ticket.
