### ISSUE TITLE
Display account information based on CBU

### ISSUE THREAD

**Issue by lukio** [tryton-ar/bank_ar#5]
Desde la implementación de #4, podemos mostrar información de la cuenta utilizando los datos del CBU. El CBU se compone de 2 bloques.

http://www.gxopen.com/forumsr/servlet/viewthread?ARTECH,1,10148#10168

Bloque 1 - 8 posiciones
3 de banco, en el caso de las CBU del banco credicoop siempre 191
4 de sucursal
1 Dígito verificador del bloque 1

Bloque 2 - 14 posiciones (BCCL)
CFASSSCCCCCCCD

Donde CF (2 posiciones) indican que se trata de una cuenta fija (un viejo concepto del banco) en el caso de las CBU del banco siempre vale "55"

A - 1 posición. Vale 0 Cuenta corriente pesos, 1 Caja de ahorro pesos, 2 caja de ahorro dolar
SSS - Sucursal de la cuenta (bank subsidiary)
CCCCCCC - Nro de cuenta incluido su dígito verificador
D - Dígito Verificador del bloque 2

Bloque 2 (general)
Identificación de la cuenta individual (13 posiciones)
Los primeros dos dígitos para identificar características de la cuenta según criterio de la Entidad (ej.: tipo de cuenta y moneda de la cuenta)
Los once dígitos siguientes para el número de cuenta (completando con ceros a izquierda cuando corresponda)
Dígito verificador de las anteriores 13 posiciones (1 posición).

**Comment by cburgosster** [comment]
Hola trabajando en trytond 5.6 y adecuando para Argentiname da el sig  Error de aplicación Fault:[bank] en el modulo bank_ar Detalles: Traceback (most recent call last):
  File "/home/usuario/.local/lib/python3.6/site-packages/tryton/gui/main.py", line 277, in do_activate
    common.Login()
  File "/home/usuario/.local/lib/python3.6/site-packages/tryton/common/common.py", line 900, in __init__
    func(parameters)
  File "/home/usuario/.local/lib/python3.6/site-packages/tryton/rpc.py", line 87, in login
    result = connection.common.db.login(username, parameters, language)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/home/usuario/.local/lib/python3.6/site-packages/tryton/jsonrpc.py", line 306, in __request
    raise Fault(*response['error'])
tryton.jsonrpc.Fault: ['bank']

Fault: ['bank']

**Comment by lukio** [comment]
Hola, te pido que abras otro ticket respecto a la instalación del módulo en la versión 5.6.

Dicho esto, los módulos de la localización argentina estan testeados y desarrollados hasta la versión LTS (5.0).
Si igualmente, quisieras utilizar este módulo en una implementación con la v5.6, tendrías que pasar la información que actualmente esta en data.xml y pasarlo a unos archivos de importación, ya que atribute skiptest fue deprecado.

* https://bugs.tryton.org/issue8735
* https://bugs.tryton.org/issue8662

**Comment by cburgosster** [comment]
Excelente gracias Lukio
