### ISSUE TITLE
bank_ar in tryton 5.6

### ISSUE THREAD

**Issue by cburgosster** [tryton-ar/bank_ar#8]
Hola trabajando en trytond 5.6 y adecuando para Argentiname da el sig Error de aplicación Fault:[bank] en el modulo bank_ar Detalles: Traceback (most recent call last):
File "/home/usuario/.local/lib/python3.6/site-packages/tryton/gui/main.py", line 277, in do_activate
common.Login()
File "/home/usuario/.local/lib/python3.6/site-packages/tryton/common/common.py", line 900, in init
func(parameters)
File "/home/usuario/.local/lib/python3.6/site-packages/tryton/rpc.py", line 87, in login
result = connection.common.db.login(username, parameters, language)
File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in call
return self.__send(self.__name, args)
File "/home/usuario/.local/lib/python3.6/site-packages/tryton/jsonrpc.py", line 306, in __request
raise Fault(*response['error'])
tryton.jsonrpc.Fault: ['bank']

Fault: ['bank']

**Comment by lukio** [comment]
Se tiene que pasar la información que actualmente esta en data.xml y pasarlo a unos archivos de importación, ya que atribute skiptest fue deprecado.

* https://bugs.tryton.org/issue8735
* https://bugs.tryton.org/issue8662

También reemplazar el raise_user_error por una exception.

**Comment by lukio** [comment]
Ejemplo de commit para pasar la data que esta en el xml, por un importador a csv:
https://hg.tryton.org/modules/country/rev/416223b2a093/

**Comment by lukio** [comment]
Hola @cburgosster, el módulo fue migrado para la versión 5.2, aunque debería funcionar correctamente en 5.6.
Igualmente, esta faltando la migración (en curso) de party_ar para que funcione completamente.

commits:

* https://github.com/tryton-ar/bank_ar/commit/0d9f28918b044e741a6741de6e6ed4b3a2ce67ba
* https://github.com/tryton-ar/bank_ar/commit/d71b36f99bb337caa9fd73ccfc1168c0fb8402e2

TODO:
* completar el archivo [bank_ar.csv](scripts/bank_ar.csv)
